name: OpenWRT LEDE

on:
  workflow_dispatch:
    inputs:
      router:
        required: true
        default: newifi-mini-y1
        type: choice
        options:
        - newifi-mini-y1
        - phicomm-k2
        - phicomm-k2p
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Deps
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 python2.7 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler g++-multilib antlr3 gperf wget curl swig rsync

      - name: Clone Lede Sources
        run: |
          git clone https://github.com/coolsnowwolf/lede

      - name: Update & Install Feeds
        run: |
          cd lede
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate Config
        run: |
          cd lede
          ls ../
          cp ../${{ github.event.inputs.router }}-config ./.config
          make defconfig

      - name: Download DL
        run: |
          cd lede
          make -j8 download V=s

      - name: Build
        run: |
          cd lede
          make -j1 V=s

      - name: Upload Artifact
        uses: actions/upload-artifact@main
        with:
          name: OpenWrt_Firmware_Newifi_Mini_Y1
          path: ./lede/bin/targets/
